### ISSUE TITLE
[Bug report - 1.16.5] Game crashes when trying to use Trash Cans v1.0.16

### ISSUE THREAD

**Issue by KuryKat** [juh9870/MoreMountedStorages#11]
### Describe your issue

Hey I was trying to update the mods made by SuperMartijn642 in my modpack to the latest version of them and when I tried loading the game it crashed, probably because the Trash Cans updated and something was removed from the code or something like that, I suppose. I'm sorry that I can't explain it properly, I'm tired right now hehe "^^

### Mod version

v1.2.0

### Forge version

36.2.39

### Create version

v0.3.2g

### Crash Report

https://mclo.gs/AP98pZK

**Comment by juh9870** [comment]
Got it. For now, you can try disabling integration in the config file and see if it would help

**Comment by KuryKat** [comment]
Okay, thanks! I instead just rolled back one version in all their mods, so this way I can still use your integration

**Comment by KuryKat** [comment]
Any update in this issue? :D

**Comment by NielsPilgaard** [comment]
> you can try disabling integration in the config file and see if it would help

This doesn't help sadly.

**Comment by juh9870** [comment]
Oof, I will try to get an update done then

**Comment by NielsPilgaard** [comment]
Thanks, I really appreciate it 😊

**Comment by juh9870** [comment]
Release is out on GitHub, and should be soon approved on CurseForge

**Comment by NielsPilgaard** [comment]
Works like a charm, thanks!

**Comment by KuryKat** [comment]
Thanks!
