### ISSUE TITLE
[Bug report - 1.18.2] Trash Cans 1.0.17a crashes game

### ISSUE THREAD

**Issue by NightOps007** [juh9870/MoreMountedStorages#14]
### Describe your issue

This is probably the same issue from the previous report: [[Bug report - 1.16.5] Game crashes when trying to use Trash Cans v1.0.16](https://github.com/juh9870/MoreMountedStorages/issues/11), just that it happens with 1.18.2 version of MC as well or Trash Cans changed something again.
[crash-2023-06-10_09.44.32-fml.txt](https://github.com/juh9870/MoreMountedStorages/files/11713004/crash-2023-06-10_09.44.32-fml.txt)

### Mod version

1.2.2

### Forge version

40.2.9

### Create version

0.5.0.i

### Crash Report

https://github.com/juh9870/MoreMountedStorages/files/11713004/crash-2023-06-10_09.44.32-fml.txt

**Comment by juh9870** [comment]
This is a wrong repository, I don't work on 1.18. Report it to
 https://github.com/Lgmrszd/CreateMountedStorages
