### ISSUE TITLE
Integration for 1.20 Forge

### ISSUE THREAD

**Issue by Punchin83** [juh9870/MoreMountedStorages#15]
### Before suggesting a mod please

- [X] I have already tested myself that the modded storages I want to suggest don't work as a part of Create moving contraption, even with More Mounted Storages installed
- [X] Storages I want to suggest don't require power of any kind to function
- [X] Storages I want to suggest are not multiblock structures
- [X] Main function of storages I want to suggest is to store items, and they don't do any kind of items processing over time

### URL

minecraft.com

**Comment by juh9870** [comment]
This is not a mod request.

I don't have any plans to port this mod past 1.16 at the moment, someone else might do it.
