### ISSUE TITLE
[SUGGESTION] Add DimStorage Support

### ISSUE THREAD

**Issue by JuicyCosmos** [juh9870/MoreMountedStorages#2]
DimStorage is a bit like EnderStorage. They basically have the same concept but I personally use DimStorage because rendering Ender Storage items in JEI crashes my client. Would it be possible to add support for the DimChests from DimStorage mod? 
Here's the curseforge page for DimStorage: https://www.curseforge.com/minecraft/mc-mods/dimstorage

**Comment by juh9870** [comment]
I will look into it before the next update

**Comment by juh9870** [comment]
Support added in v1.2.0
