### ISSUE TITLE
[Suggestion] Support for Metal Barrels

### ISSUE THREAD

**Issue by smbarbour** [juh9870/MoreMountedStorages#4]
https://www.curseforge.com/minecraft/mc-mods/metal-barrels

This mod does for barrels what Iron Chests does for chests.

**Comment by juh9870** [comment]
When I tested they worked even without my addon, don't they work for you?

**Comment by smbarbour** [comment]
Never mind then... I hadn't even tried yet. I was working on building a
pack and found this mod as an add on. Iron chests were on the list for this
mod and assumed (apparently incorrectly) that metal barrels would likewise
need some finesse to work.

**Comment by juh9870** [comment]
I will close this for now. If you face issues while using Metal Barrels on moving contraptions, feel free to open a new issue
