### ISSUE TITLE
[Request] Support for Storage Overhaul

### ISSUE THREAD

**Issue by rckymtnrfc** [juh9870/MoreMountedStorages#5]
### Before suggesting a mod please

- [X] I have already tested myself that the modded storages I want to suggest don't work as a part of Create moving contraption, even with More Mounted Storages installed
- [X] Storages I want to suggest don't require power of any kind to function
- [X] Storages I want to suggest are not multiblock structures
- [X] Main function of storages I want to suggest is to store items, and they don't do any kind of items processing over time

### URL

https://www.curseforge.com/minecraft/mc-mods/storage-overhaul

### Additional info

Thanks for considering it!

**Comment by rckymtnrfc** [comment]
I wasn't thinking and I guess this does have multiblock structures with double chests.  Not sure if that would be an issue.

**Comment by juh9870** [comment]
Double chest are fine. I will look into this mod before the next release
