### ISSUE TITLE
Mekanism storage bins

### ISSUE THREAD

**Issue by theboo** [juh9870/MoreMountedStorages#6]
### Before suggesting a mod please

- [X] I have already tested myself that the modded storages I want to suggest don't work as a part of Create moving contraption, even with More Mounted Storages installed
- [X] Storages I want to suggest don't require power of any kind to function
- [X] Storages I want to suggest are not multiblock structures
- [X] Main function of storages I want to suggest is to store items, and they don't do any kind of items processing over time

### URL

https://www.curseforge.com/minecraft/mc-mods/mekanism

### Additional info

Mekanism bins work very similarly to storage drawers or BHUs, bulk storage for one item.

(Saw y'all's conversation in enigmatica discord and that no one put in the requested issue on your tracker xD)

**Comment by TemperedFool** [comment]
haha boo you beat me to suggesting my own suggestion!

**Comment by juh9870** [comment]
Mek storage bins can't be moved by contraption, so unless this is changed, I can't add support.
