### ISSUE TITLE
Support for 1.18.1

### ISSUE THREAD

**Issue by ozma6464** [juh9870/MoreMountedStorages#7]
Support for 1.18.1 please?

**Comment by juh9870** [comment]
Sorry, but I'm not playing any 1.18 modpacks with create, so I have no interest in updating it for 1.18 for now. Anyone willing is free to do a PR with 1.18 support tho

**Comment by mrossi80** [comment]
Hope you can find some one to help, i am new to modding, so i could help only with a lot of help.

**Comment by Ch1216** [comment]
Someone is making a pr for 1.18.2 https://github.com/juh9870/MoreMountedStorages/pull/9 but idk why juh hasnt merged it yet tho unless hes ide is still broke somehow after 15 days

**Comment by yanang007** [comment]
Please note that it is inpolite to ask the author to do anything.
If you do really need this mod now, you may compile the snapshot version from source in my repo with jitpack or your own development environment.

**Comment by ozma6464** [comment]
> Please note that it is inpolite to ask the author to do anything. If you do really need this mod now, you may compile the snapshot version from source in my repo with jitpack or your own development environment.

And please note that it is in fact NOT impolite to ask a simple yes or no question. It IS impolite, however, to randomly comment on a topic to for the sole purpose to chastise a simple request.
Secondly, not everyone has the knowledge or ability to do their own development work.

If the author has no interest to update then that is fine, They answered the question and that was that.

**Comment by yanang007** [comment]
> > Please note that it is inpolite to ask the author to do anything. If you do really need this mod now, you may compile the snapshot version from source in my repo with jitpack or your own development environment.
> 
> And please note that it is in fact NOT impolite to ask a simple yes or no question. It IS impolite, however, to randomly comment on a topic to for the sole purpose to chastise a simple request. Secondly, not everyone has the knowledge or ability to do their own development work.
> 
> If the author has no interest to update then that is fine, They answered the question and that was that.

I'm sorry for not quoting the comment I was replying to and the misunderstanding it made. 
What it mean is that someone in the comments is doing this in a little bit inpolite way. I don't think there is anything wrong with you. I'm really sorry if you feel offended.


> Someone is making a pr for 1.18.2 #9 but idk why juh hasnt merged it yet tho unless hes ide is still broke somehow after 15 days

I'm the someone who is working on a port, but it would be probably not a good idea to push him too hard.

**Comment by ozma6464** [comment]
> I'm sorry for not quoting the comment I was replying to and the misunderstanding it made.
> What it mean is that someone in the comments is doing this in a little bit inpolite way. I don't think there is anything wrong with you. I'm really sorry if you feel offended.

No worries, simple misunderstanding.
