### ISSUE TITLE
[Request] Support for More Storage Drawers

### ISSUE THREAD

**Issue by DarkYuan** [juh9870/MoreMountedStorages#8]
### Before suggesting a mod please

- [X] I have already tested myself that the modded storages I want to suggest don't work as a part of Create moving contraption, even with More Mounted Storages installed
- [X] Storages I want to suggest don't require power of any kind to function
- [X] Storages I want to suggest are not multiblock structures
- [X] Main function of storages I want to suggest is to store items, and they don't do any kind of items processing over time

### URL

https://www.curseforge.com/minecraft/mc-mods/more-storage-drawers

### Additional info

Adds storage drawer compat for various mods' woods. Confirmed that it doesn't work with an Ebony 1x1 from Oh The Biomes You'll Go.

**Comment by juh9870** [comment]
Okay, will check it out before the next update
